### PR TITLE
fixes for cross-compilation of doslib

### PR DESCRIPTION
**Pull request by jmalak**
- fix include path list, list is defined by WATCOM_INCLUDE macro for target independly on host platform
   (OW tools -x option ensure ignoring of INCLUDE environmet variable, which is used for host default setup)
   OW prior version 2.0 doesn't support -x option, it requires cleanup of INCLUDE env.variable
   (by wmake directive .BEFORE with set INCLUDE=)
- remove separator $(HPS) macros because !include directive in make file support forward slash for file name on any host
- fix too long lines
- remove WATCOM_INCLUDE from AFLAGS, Open Watcom doesn't have any assembly related header files
- add WATCOM_INCLUDE for DOS targets

### CODE REVIEW

**Comment by jmalak** [comment]
Fix was relatively simple
for OW2.0 use -x option (ignore INCLUDE env.variable) and add all OW header path (for target) to WATCOM_INCLUDE, which is add to compiler command line
remove this mechanism for assembler because OW has not any header file for it
rest of changes was not necessary but clear include path that doesn't use $(HPS) macro
I test only compilation by OW1.9 and OW2.0 without any problem

Now standard OW environment variable should be setup for Linux host before run any build.
It looks like this
export WATCOM=/home/jiri/ow-v2/rel
export PATH=$WATCOM/binl:$WATCOM/binw:$PATH
export EDPATH=$WATCOM/eddat
export INCLUDE=$WATCOM/lh
don't forgot include $WATCOM/binw: on the PATH, it is necessary for linker to find stubs etc.

**Comment by joncampbell123** [comment]
I did not know you could split lines like that in a *.mak file:

wlib -q -b -c $(EXT_LAME_LIB) &
    -+$(SUBDIR)$(HPS)bitstream.obj &
    -+$(SUBDIR)$(HPS)encoder.obj &
    -+$(SUBDIR)$(HPS)fft.obj &
...

**Comment by jmalak** [comment]
It is better readable. generaly '&' character is continuation of line in wmake make files

**Comment by joncampbell123** [comment]
I'll keep that in mind, it makes it easier to see what was added to the list through git diff.

**Pull request merged**
